#!/usr/bin/env python3
"""Rookery bootstrap — builds a self-contained zipapp and generates the
one-liner installer script that peers run to get `rookery` onto PATH.

Two public functions:
  build_pyz(output_path)       -> str   build the zipapp; return output_path
  installer_script(public_url) -> str   return a Python installer script (as a
                                        string) suitable for `curl ... | python3 -`
"""

import os
import shutil
import stat
import tempfile
import zipapp

# ---------------------------------------------------------------------------
# Source files to bundle (relative to this file's directory).
# All are peer-side modules that a fresh machine needs.
# ---------------------------------------------------------------------------
_ROOKERY_DIR = os.path.dirname(os.path.abspath(__file__))

_PY_MODULES = [
    "rookery_cli.py",
    "cli_serve.py",
    "cli_up.py",
    "cli_approve.py",
    "identity.py",
    "known_hosts.py",
    "discovery.py",
    "config_manager.py",
    "mailctl.py",
    "rookery_mcp.py",
    "rookery.py",
    "security.py",
    "handshake.py",
]

_DATA_FILES = [
    "schema.sql",
]

_MAIN_PY = """\
import rookery_cli
rookery_cli.main()
"""


def build_pyz(output_path: str) -> str:
    """Stage peer modules into a temp dir, then zip them into a
    self-contained executable at *output_path*.  Returns *output_path*.
    """
    stage = tempfile.mkdtemp(prefix="rookery_pyz_")
    try:
        # Copy Python modules
        for fname in _PY_MODULES:
            src = os.path.join(_ROOKERY_DIR, fname)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(stage, fname))

        # Copy data files
        for fname in _DATA_FILES:
            src = os.path.join(_ROOKERY_DIR, fname)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(stage, fname))

        # Write __main__.py so `python3 rookery.pyz` dispatches to the CLI
        with open(os.path.join(stage, "__main__.py"), "w") as fh:
            fh.write(_MAIN_PY)

        # Build the zipapp
        zipapp.create_archive(
            stage,
            target=output_path,
            interpreter="/usr/bin/env python3",
        )

        # Make it executable
        os.chmod(
            output_path,
            stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
        )  # 0755

    finally:
        shutil.rmtree(stage, ignore_errors=True)

    return output_path


def installer_script(public_url: str) -> str:
    """Return a Python script (as a string) that downloads the rookery zipapp
    from *public_url*/bootstrap?pyz=1 and installs it at ~/.local/bin/rookery.

    The returned string is intended to be piped into `python3 -`:
        curl -sSL http://A:8765/bootstrap | python3 -
    """
    return f"""\
#!/usr/bin/env python3
# Rookery one-liner installer — generated by bootstrap.installer_script()
# Usage:  curl -sSL {public_url}/bootstrap | python3 -
import os
import stat
import urllib.request

DEST = os.path.expanduser("~/.local/bin/rookery")
PYZ_URL = "{public_url}/bootstrap?pyz=1"

os.makedirs(os.path.dirname(DEST), exist_ok=True)
print(f"Downloading rookery from {{PYZ_URL}} ...")
urllib.request.urlretrieve(PYZ_URL, DEST)
os.chmod(DEST, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
print(f"OK rookery installed at {{DEST}}  (run: rookery up <url>)")
"""
